### ISSUE TITLE
[FEATURE] Add missing relational operators

### ISSUE THREAD

**Issue by BigBadE** [BigBadE/Raven-Language#13]
**Describe Your Feature**
Add missing relational operators: <, >, <=, >=

**Provide a Code Snippet Using Your Feature**
```rust
fn test() -> bool {
    return 2 > 1;
}
```

**Prerequisites**
The Order trait #14 

**Additional Information**
All relational operators should be implemented like the equals operator and all combination operators (>= and <=) should be implemented like NotEquals, where it's automatically implemented for everything that implements < and >.

Should be automatically implemented on everything that implements the Ordered trait.

**Comment by a11155** [comment]
Hey, I am Andrii. I will work on this

**Comment by gabrielmikhail** [comment]
Hey its Gabriel , I can work on this one

**Comment by BigBadE** [comment]
Implemented in #24
