### ISSUE TITLE
[BUG] New line at the end of file causes error

### ISSUE THREAD

**Issue by Jeremy924** [BigBadE/Raven-Language#23]
**Describe the bug**
The program produces an error when there is a new line at the end of the file. 

**Raven Code To Reproduce**
```
fn main() {}

```

**Error Output or Unexpected Behavior**
```
...\Raven-Language\language\compilers\llvm\src\lib.rs   |
:61:35:
called `Option::unwrap()` on a `None` valueInvalid top element!
```
**Additional context**

**Comment by BigBadE** [comment]
Fixed in #27
