### ISSUE TITLE
Replacing Placeholder Errors with Real ParsingErrors

### ISSUE THREAD

**Issue by Pillber** [BigBadE/Raven-Language#5]
Not a bug, but noting this down here.

Currently, within the Raven codebase, most ParsingErrors are actually just placeholder errors, with no real knowledge on the file and place in file where error occurred, and just a message of what when wrong. This is a place to discuss the implementation of finding and replacing all placeholder errors with appropriate ParsingErrors.

The Token struct holds the position of a specific token without reference to the file that it is in. From a token, the `Token::make_error(file, error_message)` function can be called to create an error from that token. However, the file the token is found in is not a part of that token. A wrapper (possibly FileToken?) for a token with a file should be created so the error can be easily created from the token, as the file name is stored with the token.

From there, any place where a placeholder_error is currently being created, a reference to the FileToken should be able to be accessed so the error can be replaced with the FileToken::make_error(message) function. This is where I lose the thread, because I wouldn't know how to access that token.

That's my basic idea! Discussion on further implementation or better ways to go about this would be appreciated.

**Comment by BigBadE** [comment]
Re-made this with the feature template for #6, please comment on it if you want to be assigned to it
