### ISSUE TITLE
[FEATURE] Replacing Placeholder Issues With Real Errors

### ISSUE THREAD

**Issue by BigBadE** [BigBadE/Raven-Language#6]
**Describe Your Feature**
Currently, within the Raven codebase, most ParsingErrors are actually just placeholder errors, with no real knowledge on the file and place in file where error occurred, and just a message of what when wrong. This is a place to discuss the implementation of finding and replacing all placeholder errors with appropriate ParsingErrors.

**Provide a Code Snippet Using Your Feature**
Not Applicable

**Additional Information**
The Token struct holds the position of a specific token without reference to the file that it is in. From a token, the Token::make_error(file, error_message) function can be called to create an error from that token. However, the file the token is found in is not a part of that token. A wrapper (possibly FileToken?) for a token with a file should be created so the error can be easily created from the token, as the file name is stored with the token.

From there, any place where a placeholder_error is currently being created, a reference to the FileToken should be able to be accessed so the error can be replaced with the FileToken::make_error(message) function. This is where I lose the thread, because I wouldn't know how to access that token.

**Comment by Pillber** [comment]
In [verify_effect](https://github.com/BigBadE/Raven-Language/blob/76e23b1f45590eab7bb77d9d24d4dab52793fb17/language/checker/src/check_code.rs#L46) of check_code.rs and [verify_function_code](https://github.com/BigBadE/Raven-Language/blob/76e23b1f45590eab7bb77d9d24d4dab52793fb17/language/checker/src/check_function.rs#L49) of check_function.rs, FileTokens should be associated to [Effects](https://github.com/BigBadE/Raven-Language/blob/76e23b1f45590eab7bb77d9d24d4dab52793fb17/language/syntax/src/code.rs#L108) and [CodelessFinalizedFunctions](https://github.com/BigBadE/Raven-Language/blob/76e23b1f45590eab7bb77d9d24d4dab52793fb17/language/syntax/src/function.rs#L131) in order to pass the exact token where parsing errors occur.

**Comment by Pillber** [comment]
The [code_parser](https://github.com/BigBadE/Raven-Language/blob/d73c6b32ff397b19e16425159179e1d5c45fc077/language/parser/src/parser/code_parser.rs#L44C8-L44C18) and similar files handle the creation of Effects, therefore FileTokens should be somehow linked the the effects in there. At that point, we still have access to the file, so FileTokens should be made at that time and passed to the Effect as necessary.

**Comment by BigBadE** [comment]
control_parser.rs line 96:
```rust
    let start = parser_utils.tokens[parser_utils.index].start;
    let start_offset = parser_utils.tokens[parser_utils.index].start_offset;
    
    // Gets the variable we're looping over
    let effect = parse_line(parser_utils, ParseState::ControlVariable)?;
    if effect.is_none() {
        return Err(parser_utils.tokens.get(parser_utils.index).unwrap().make_error(
            parser_utils.file.clone(), "Expected iterator, found void".to_string()));
    }
    
    let value_token = Token::new(TokenTypes::EOF, None, start, start_offset, 
    parser_utils.tokens[parser_utils.index-1].end, parser_utils.tokens[parser_utils.index-1].end_offset);
```

**Comment by Pillber** [comment]
Places with placeholder errors, and the Effect that calls it. The ones with question marks do not have an associated effect
### Check Code
#### verify_code
- [ ] ExpressionType::Return
#### verify_effect
- [ ] Effects::Operation
- [ ] Effects::ImplementationCall
- [ ] Effects::MethodCall
- [ ] Effects::CreateStruct
- [ ] Effects::CreateVariable
- [ ] Effects::CreateArray
#### degeneric_header
- [ ] ???
#### check_method
- [ ] ???
### Check Function
#### verify_function_code
- [ ] ???
