### ISSUE TITLE
[BUG] Adding character to int causes compiler infinite loop

### ISSUE THREAD

**Issue by Pillber** [BigBadE/Raven-Language#63]
**Describe the bug**
The title. When a character is the second operand of an addition (or subtraction), the compiler infinite loops somewhere.

**Raven Code To Reproduce**
Anywhere in a raven file:
```
let test = 1 + '0';
```

**Error Output or Unexpected Behavior**
Compiler infinite loop.

**Additional context**

**Comment by BigBadE** [comment]
Fixed
