### ISSUE TITLE
[FEATURE] Logical and Bitwise AND, OR, XOR, and NOT operators

### ISSUE THREAD

**Issue by BigBadE** [BigBadE/Raven-Language#8]
**Describe Your Feature**
Add an implementation for logical AND (&&), OR (||), XOR (^^), and NOT (!) and bitwise AND (&), OR(|) XOR(^) and NOT (~)

**Provide a Code Snippet Using Your Feature**
```rust
fn test() -> bool {
    // 1 & 3 == 1, 3 | 8 == 11
    let testing = (1 & 3) | 8;
    // 11 ^ 5 == 14
    let testing ^= 5;
    return testing == 14 && (1 != 2 || ~0 != 20);
}
```

**Additional Information**
This will require adding additional internal operators, look at how add, subtract, etc... is implemented

**Comment by Jeremy924** [comment]
I will work on this.

**Comment by WilliamAalund** [comment]
I am interested in working on this.
